/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Modelo.Tiempo;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diego Valdes
 */
public class Parametros extends javax.swing.JFrame {

    /**
     * Creates new form Parametros
     */
    int nLlegadas;
    int nSalidas;
    
    private ArrayList<ArrayList> tiemposSalidas;
    
    
    public Parametros() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        nLlegadas = 0;
        nSalidas = 0;
        
        tiemposSalidas = new ArrayList<ArrayList>();
        
        initTablas();
    }
    
    public void initTablas(){
        DefaultTableModel modelLlegada = new DefaultTableModel();
        modelLlegada.addColumn("Tiempo");
        modelLlegada.addColumn("Probabilidad");

        this.jTableLlegadas.setModel(modelLlegada);
    }
    
    public void addTiempoSalida(ArrayList<Tiempo> tiempos){
        tiemposSalidas.add(tiempos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelHoras = new javax.swing.JLabel();
        jTextFieldEstaciones = new javax.swing.JTextField();
        jLabelEstaciones = new javax.swing.JLabel();
        jTextFieldMaxClientes = new javax.swing.JTextField();
        jLabelMaxClientes = new javax.swing.JLabel();
        jTextFieldHoras = new javax.swing.JTextField();
        jTextFieldDias = new javax.swing.JTextField();
        jLabelDias = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLlegadas = new javax.swing.JTable();
        jLabelLlegadas = new javax.swing.JLabel();
        jButtonAgregarTiempoLlegada = new javax.swing.JButton();
        jTextFieldTiempoLlegadas = new javax.swing.JTextField();
        jLabelTiempoLlegadas = new javax.swing.JLabel();
        jButtonIniciar = new javax.swing.JButton();
        jButtonEliminarProbLlegada = new javax.swing.JButton();
        jTextFieldProbLlegadas = new javax.swing.JTextField();
        jLabelProbabilidadLlegadas = new javax.swing.JLabel();
        jButtonTiempoSalidas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 400));

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 400));

        jLabelHoras.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelHoras.setText("Horas de jornada");

        jTextFieldEstaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEstacionesActionPerformed(evt);
            }
        });

        jLabelEstaciones.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelEstaciones.setText("Numero de estaciones");

        jTextFieldMaxClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMaxClientesActionPerformed(evt);
            }
        });

        jLabelMaxClientes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMaxClientes.setText("Cantidad maxima clientes");

        jTextFieldHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHorasActionPerformed(evt);
            }
        });

        jTextFieldDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDiasActionPerformed(evt);
            }
        });

        jLabelDias.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelDias.setText("Dias de simulacion");

        jTableLlegadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableLlegadas);

        jLabelLlegadas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLlegadas.setText("Tiempo entre llegadas");

        jButtonAgregarTiempoLlegada.setText("Agregar");
        jButtonAgregarTiempoLlegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarTiempoLlegadaActionPerformed(evt);
            }
        });

        jTextFieldTiempoLlegadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTiempoLlegadasActionPerformed(evt);
            }
        });

        jLabelTiempoLlegadas.setText("Tiempo");

        jButtonIniciar.setBackground(new java.awt.Color(0, 102, 0));
        jButtonIniciar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIniciar.setText("Iniciar Simulacion");
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });

        jButtonEliminarProbLlegada.setText("Eliminar");
        jButtonEliminarProbLlegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarProbLlegadaActionPerformed(evt);
            }
        });

        jTextFieldProbLlegadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProbLlegadasActionPerformed(evt);
            }
        });

        jLabelProbabilidadLlegadas.setText("Probabilidad");

        jButtonTiempoSalidas.setBackground(new java.awt.Color(0, 0, 102));
        jButtonTiempoSalidas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTiempoSalidas.setText("Tiempos de salida");
        jButtonTiempoSalidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTiempoSalidasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jButtonIniciar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEstaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEstaciones)
                            .addComponent(jTextFieldMaxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDias)
                            .addComponent(jLabelMaxClientes)
                            .addComponent(jTextFieldDias, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonTiempoSalidas)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonAgregarTiempoLlegada)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEliminarProbLlegada))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelProbabilidadLlegadas)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTiempoLlegadas, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldProbLlegadas, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelLlegadas)
                    .addComponent(jLabelTiempoLlegadas)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDias)
                    .addComponent(jLabelLlegadas))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabelHoras)
                        .addGap(6, 6, 6)
                        .addComponent(jTextFieldHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldTiempoLlegadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelTiempoLlegadas))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldProbLlegadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelProbabilidadLlegadas)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonAgregarTiempoLlegada)
                                    .addComponent(jButtonEliminarProbLlegada))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(jButtonIniciar)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabelMaxClientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldMaxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelEstaciones)
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldEstaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonTiempoSalidas)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldProbLlegadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProbLlegadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProbLlegadasActionPerformed

    private void jButtonEliminarProbLlegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarProbLlegadaActionPerformed

        int filaSelect = jTableLlegadas.getSelectedRow();
        
        if(filaSelect >= 0){
            DefaultTableModel model = (DefaultTableModel) this.jTableLlegadas.getModel();
            model.removeRow(filaSelect);
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione una fila de la tabla");
        }
    }//GEN-LAST:event_jButtonEliminarProbLlegadaActionPerformed

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed

        if(jTextFieldDias.getText().equals("") || jTextFieldEstaciones.getText().equals("") ||
            jTextFieldHoras.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Los parametros no pueden estas vacios");
        }else{
            try{
                int dias = Integer.parseInt(jTextFieldDias.getText());
                int horas = Integer.parseInt(jTextFieldHoras.getText());
                int estaciones = Integer.parseInt(jTextFieldEstaciones.getText());
                
                int maxClientes;
                if(jTextFieldMaxClientes.getText().equals("")){
                    maxClientes = Simulacion.Infinito;
                }else{
                    maxClientes = Integer.parseInt(jTextFieldMaxClientes.getText());
                }
                
                if(dias > 0  && horas > 0 && maxClientes > 0 && estaciones > 0){
                    float cont = 0;
                    
                    for(int i=0; i<jTableLlegadas.getRowCount(); i++){
                        cont += Float.parseFloat(jTableLlegadas.getValueAt(i, 1).toString());
                    }
                    
                    if(cont == 1){
                        //Empezar a tomar valores de las estaciones
                        
                        ArrayList tiemposLlegadas = new ArrayList<Tiempo>();
                        
                        for(int i=0; i<jTableLlegadas.getRowCount(); i++){
                            tiemposLlegadas.add(new Tiempo(Integer.parseInt(jTableLlegadas.getValueAt(i, 0).toString()),
                                                Float.parseFloat(jTableLlegadas.getValueAt(i, 1).toString())));
                        }
                        
                        if(tiemposSalidas.size() == estaciones){
                            new Simulacion(dias, horas, estaciones, maxClientes, tiemposLlegadas, tiemposSalidas).setVisible(true);
                            this.dispose();
                        }else{
                            JOptionPane.showMessageDialog(this, "Coloque los tiempos de salida");
                        }
                        
                    }else{
                        JOptionPane.showMessageDialog(this, "La suma de las probabilidades debe ser igual a 1.");
                    }
                }else{
                   JOptionPane.showMessageDialog(this, "Solo se admiten valores positivos"); 
                }

            }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(this, "Solo se admiten valores numericos");
            }
        }
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    private void jTextFieldTiempoLlegadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTiempoLlegadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTiempoLlegadasActionPerformed

    private void jButtonAgregarTiempoLlegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarTiempoLlegadaActionPerformed

        if(jTextFieldTiempoLlegadas.getText().equals("") || jTextFieldProbLlegadas.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Los parametros no pueden estas vacios");
        }else{
            try{
                int tiempo = Integer.parseInt(jTextFieldTiempoLlegadas.getText());
                float probabilidad = Float.parseFloat(jTextFieldProbLlegadas.getText());

                if(tiempo > 0 && probabilidad > 0){
                    String[] llegada = {String.valueOf(tiempo), String.valueOf(probabilidad)};

                    DefaultTableModel model = (DefaultTableModel) this.jTableLlegadas.getModel();
                    model.addRow(llegada);
                }else{
                    JOptionPane.showMessageDialog(this, "Solo se admiten valores positivos");
                }
                
            }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(this, "Solo se admiten valores numericos");
            }
        }
    }//GEN-LAST:event_jButtonAgregarTiempoLlegadaActionPerformed

    private void jTextFieldDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDiasActionPerformed

    private void jTextFieldHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHorasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHorasActionPerformed

    private void jTextFieldMaxClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaxClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaxClientesActionPerformed

    private void jTextFieldEstacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEstacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEstacionesActionPerformed

    private void jButtonTiempoSalidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTiempoSalidasActionPerformed
        
        try{
            int estaciones = Integer.parseInt(jTextFieldEstaciones.getText());
            
            if(estaciones > 0){
                for(int i=0; i<estaciones; i++){
                    //Pedir tiempo entre salidas
                    TiempoSalidas tiempoSalidasInterfaz = new TiempoSalidas(this, i+1);
                    tiempoSalidasInterfaz.setVisible(true);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Solo se admiten valores positivos");
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Solo se admiten valores numericos");
            
        }
        
        
    }//GEN-LAST:event_jButtonTiempoSalidasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Parametros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarTiempoLlegada;
    private javax.swing.JButton jButtonEliminarProbLlegada;
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JButton jButtonTiempoSalidas;
    private javax.swing.JLabel jLabelDias;
    private javax.swing.JLabel jLabelEstaciones;
    private javax.swing.JLabel jLabelHoras;
    private javax.swing.JLabel jLabelLlegadas;
    private javax.swing.JLabel jLabelMaxClientes;
    private javax.swing.JLabel jLabelProbabilidadLlegadas;
    private javax.swing.JLabel jLabelTiempoLlegadas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLlegadas;
    private javax.swing.JTextField jTextFieldDias;
    private javax.swing.JTextField jTextFieldEstaciones;
    private javax.swing.JTextField jTextFieldHoras;
    private javax.swing.JTextField jTextFieldMaxClientes;
    private javax.swing.JTextField jTextFieldProbLlegadas;
    private javax.swing.JTextField jTextFieldTiempoLlegadas;
    // End of variables declaration//GEN-END:variables
}
