/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Modelo.Cliente;
import Modelo.Cola;
import Modelo.Estacion;
import Modelo.Global;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diego Valdes
 */
public class Simulacion extends javax.swing.JFrame {
    public static DefaultTableModel modelCliente;
    public static DefaultTableModel modelEvento;

    /**
     * Creates new form Simulacion
     */
    public Simulacion(int MaxTMd, int MaxTMm, int NumeroEstaciones, int EMinima, int EMaxima,
            int SMinima, int SMaxima) {
        initComponents();
        this.setLocationRelativeTo(null);
        modelCliente = new DefaultTableModel();
        modelCliente.addColumn("Cliente");
        modelCliente.addColumn("Entrada");
        modelCliente.addColumn("Salida");
        this.tablaCliente.setModel(modelCliente);
        
        modelEvento = new DefaultTableModel();
        modelEvento.addColumn("# Evento");
        modelEvento.addColumn("Tipo de evento");
        modelEvento.addColumn("# Cliente");
        modelEvento.addColumn("TMd");
        modelEvento.addColumn("TMm");
        modelEvento.addColumn("SS");
        modelEvento.addColumn("WL");
        modelEvento.addColumn("AT");
        modelEvento.addColumn("DT");
        modelEvento.addColumn("Estacion");
        this.tablaEvento.setModel(modelEvento);
        
        Cola simulacionCola = new Cola(MaxTMd, MaxTMm, NumeroEstaciones, EMinima, EMaxima,
            SMinima, SMaxima); 
        
    }
    
    public static void AnunciarCliente(Cliente cliente){
        String[] datos = new String[]{
            String.valueOf(cliente.getNumeroCliente()),
            String.valueOf(cliente.getEntrada()),
            String.valueOf(cliente.getSalida())
        };

        modelCliente.addRow(datos);
    }
    
    public static void AnunciarEvento(String evento, Cliente cliente, Estacion estacion, Global global){
        String[] datos = new String[]{
            String.valueOf(++global.Evento),
            evento,
            String.valueOf(cliente.getNumeroCliente()),
            String.valueOf(global.TMd),
            String.valueOf(global.TMm),
            String.valueOf(estacion.CountServidoresOcupados()),
            String.valueOf(estacion.getCola().size()),
            String.valueOf(global.AT),
            String.valueOf(global.DT),
            String.valueOf(estacion.getIdEstacion())
        };
        
        modelEvento.addRow(datos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCliente = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaEvento = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        tablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaCliente);

        tablaEvento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaEvento);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 157, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaCliente;
    private javax.swing.JTable tablaEvento;
    // End of variables declaration//GEN-END:variables
}
